### ISSUE TITLE
لغت فارسی برای Image در حوزه کامپیوتر و فناوری

### ISSUE THREAD

**Issue by m4h4n** [5j9/farhangestan#1]
سلام
لغت 
Image
که امروزه استفاده فراوانی میشود در بخش های مختلف، علاوه بر استفاده برای تصاویر بصری، برای سرویس های آنلاین، و حتی فایل های پشتیبان هم استفاده میشود.
نمونه استفاده از این کلمه در لینک های زیر قابل مشاهده هست که در زبان فارسی با عنوان تصویر ترجمه میشود که اصلا معنی و مفهوم در خوری نیست :
https://en.wikipedia.org/wiki/Disk_image
https://docs.docker.com/engine/docker-overview/

جایی برای تماس برقرار کردن با فرهنگستان کشور پیدا نکردم تا این رو مطرح کنم، شما که دستتون تو کاره زحمتشو بکشید.

**Comment by 5j9** [comment]
<div dir=rtl>
سلام، من با مسئولان فرهنگستان در ارتباط نیستم. صفحهٔ «ارتباط با ما»ی وب‌گاه فرهنگستان را امتحان کنید یا مستقیماً با روابط‌عمومی آن تماس بگیرید:
</div>

https://apll.ir/%d8%a7%d8%b1%d8%aa%d8%a8%d8%a7%d8%b7/
